Tum: derleme ac

derleme:
	g++ -I ./include/ -o ./lib/Doku.o -c ./src/Doku.cpp
	g++ -I ./include/ -o ./lib/Hucre.o -c ./src/Hucre.cpp
	g++ -I ./include/ -o ./lib/Organ.o -c ./src/Organ.cpp
	g++ -I ./include/ -o ./lib/Queue.o -c ./src/Queue.cpp
	g++ -I ./include/ -o ./lib/Radix.o -c ./src/Radix.cpp
	g++ -I ./include/ -o ./lib/Agac.o -c ./src/Agac.cpp
	g++ -I ./include/ -o ./lib/Node.o -c ./src/Node.cpp
	g++ -I ./include/ -o ./lib/Sistemler.o -c ./src/Sistemler.cpp
	g++ -I ./include/ -o ./lib/Organizma.o -c ./src/Organizma.cpp
	g++ -I ./include/ -o ./lib/Kontrol.o -c ./src/Kontrol.cpp
	g++ -I ./include/ -o ./bin/Main ./lib/Doku.o ./lib/Hucre.o ./lib/Kontrol.o ./lib/Node.o ./lib/Organizma.o ./lib/Sistemler.o ./lib/Organ.o ./lib/Queue.o ./lib/Agac.o ./lib/Radix.o ./src/Main.cpp
ac:
	./bin/Main
	